CREATE DATABASE TiendaComputo;
USE TiendaComputo;

-- tablas de estados 

CREATE TABLE TBL_ESTADOS_SISTEMA (
    ID_ESTADO_SISTEMA INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(50) NOT NULL -- Activo, Inactivo, Descontinuado
);

CREATE TABLE TBL_ESTADOS_USUARIOS (
    ID_ESTADO_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(50) NOT NULL -- Activo, Suspendido, Baneado, Pendiente de Verificación
);

CREATE TABLE TBL_ESTADOS_VENTA (
    ID_ESTADO_VENTA INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(50) NOT NULL -- Pendiente, Pagado, Enviado, Entregado, Cancelado
);

CREATE TABLE TBL_CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_CATEGORIA VARCHAR(100) NOT NULL,
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES TBL_ESTADOS_SISTEMA(ID_ESTADO_SISTEMA)
);

CREATE TABLE TBL_MARCAS (
    ID_MARCA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_MARCA VARCHAR(100) NOT NULL,
    ID_ESTADO INT,
    FOREIGN KEY (ID_ESTADO) REFERENCES TBL_ESTADOS_SISTEMA(ID_ESTADO_SISTEMA)
);

CREATE TABLE TBL_USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROL VARCHAR(50),
    ID_ESTADO_USUARIO INT, -- Usando la tabla específica de usuarios
    FOREIGN KEY (ID_ESTADO_USUARIO) REFERENCES TBL_ESTADOS_USUARIOS(ID_ESTADO_USUARIO)
);

CREATE TABLE TBL_DIRECCIONES (
    ID_DIRECCION INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    PROVINCIA VARCHAR(50),
    CANTON VARCHAR(50),
    DIRECCION_EXACTA TEXT,
    ID_ESTADO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_ESTADO) REFERENCES TBL_ESTADOS_SISTEMA(ID_ESTADO_SISTEMA)
);

CREATE TABLE TBL_PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_MARCA INT,
    ID_CATEGORIA INT,
    NOMBRE VARCHAR(150) NOT NULL,
    DESCRIPCION TEXT,
    PRECIO DECIMAL(10, 2) NOT NULL,
    CANTIDAD INT NOT NULL,
    ID_ESTADO INT,
    FOREIGN KEY (ID_MARCA) REFERENCES TBL_MARCAS(ID_MARCA),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES TBL_CATEGORIAS(ID_CATEGORIA),
    FOREIGN KEY (ID_ESTADO) REFERENCES TBL_ESTADOS_SISTEMA(ID_ESTADO_SISTEMA)
);

CREATE TABLE TBL_CARRITO (
    ID_CARRITO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIOS(ID_USUARIO)
);

CREATE TABLE TBL_ITEM_CARRITO (
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
    ID_CARRITO INT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    FOREIGN KEY (ID_CARRITO) REFERENCES TBL_CARRITO(ID_CARRITO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES TBL_PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE TBL_FACTURAS (
    ID_FACTURA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_DIRECCION INT,
    TOTAL DECIMAL(10, 2),
    ID_ESTADO_VENTA INT, -- Relación con estados de venta
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_DIRECCION) REFERENCES TBL_DIRECCIONES(ID_DIRECCION),
    FOREIGN KEY (ID_ESTADO_VENTA) REFERENCES TBL_ESTADOS_VENTA(ID_ESTADO_VENTA)
);

CREATE TABLE TBL_DETALLE_FACT (
    ID_DETALLE INT PRIMARY KEY AUTO_INCREMENT,
    ID_FACTURA INT,
    ID_PRODUCTO INT,
    CANTIDAD INT,
    PRECIO_UNITARIO_MOMENTO DECIMAL(10,2),
    FOREIGN KEY (ID_FACTURA) REFERENCES TBL_FACTURAS(ID_FACTURA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES TBL_PRODUCTOS(ID_PRODUCTO)
);