DELIMITER //
CREATE PROCEDURE SP_ConsultarTecnicos()
BEGIN
    SELECT 
        T.ID_TECNICO, 
        T.NOMBRE, 
        T.EMAIL, 
        T.TELEFONO, 
        T.ESPECIALIDAD, 
        E.DESCRIPCION AS ESTADO
    FROM TBL_TECNICOS T
    INNER JOIN TBL_ESTADOS_SISTEMA E ON T.ID_ESTADO = E.ID_ESTADO_SISTEMA;
END //
DELIMITER ;